# Generated by Django 5.2.17 on 2026-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_chatmessage_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
