# Generated by Django 5.2.17 on 2026-09-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
