# Generated by Django 5.2.17 on 2026-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_savedview'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
