# Generated by Django 5.2.17 on 2026-09-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_calendarevent_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacenotification',
            name='target_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workspacenotification',
            name='target_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
