# Generated by Django 5.2.17 on 2026-09-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_directconversation_directmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='DirectConversation',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
