# Generated by Django 5.2.17 on 2026-09-03 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_execution_foundation(apps, schema_editor):
    Workspace = apps.get_model('tasks', 'Workspace')
    Task = apps.get_model('tasks', 'Task')
    LookupValue = apps.get_model('tasks', 'LookupValue')
    TaskCodeRegistry = apps.get_model('tasks', 'TaskCodeRegistry')
    TaskSupporter = apps.get_model('tasks', 'TaskSupporter')

    for workspace in Workspace.objects.all().iterator():
        sequence = 1
        used_codes = set(Task.objects.filter(workspace_id=workspace.id).exclude(code='').values_list('code', flat=True))
        tasks = Task.objects.filter(workspace_id=workspace.id).order_by('id')
        for task in tasks.iterator():
            code = (task.code or '').strip()
            if not code:
                prefix = (slugify(workspace.slug or workspace.name).replace('-', '')[:8] or 'TASK').upper()
                while f'{prefix}-{sequence:06d}' in used_codes:
                    sequence += 1
                code = f'{prefix}-{sequence:06d}'
                task.code = code
                sequence += 1
            used_codes.add(code)
            update_fields = ['code']
            if task.status == 'done':
                task.progress_percent = 100
                update_fields.append('progress_percent')
                if task.completed_at:
                    task.actual_completion_date = task.completed_at.date()
                    update_fields.append('actual_completion_date')
            for kind, legacy_field, relation_field in (
                ('workstream', 'workstream', 'workstream_ref'),
                ('phase', 'phase', 'phase_ref'),
            ):
                name = (getattr(task, legacy_field) or '').strip()
                if name:
                    lookup, _ = LookupValue.objects.get_or_create(
                        workspace_id=workspace.id,
                        project_id=task.project_ref_id,
                        kind=kind,
                        slug=slugify(name)[:140] or kind,
                        defaults={'name': name},
                    )
                    setattr(task, f'{relation_field}_id', lookup.id)
                    update_fields.append(relation_field)
            task.save(update_fields=update_fields)
            TaskCodeRegistry.objects.get_or_create(workspace_id=workspace.id, code=code, defaults={'task_id': task.id})
            if task.supporter_id:
                TaskSupporter.objects.get_or_create(task_id=task.id, user_id=task.supporter_id)
        workspace.next_task_number = max(sequence, tasks.count() + 1)
        workspace.save(update_fields=['next_task_number'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_importrun_notificationdelivery_workspacesetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='due_soon_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='week_anchor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='blocker_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='next_task_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('workstream', 'Workstream'), ('phase', 'Phase / quarter')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lookup_values', to='tasks.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_values', to='tasks.workspace')),
            ],
            options={
                'ordering': ['kind', 'position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='phase_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_tasks', to='tasks.lookupvalue'),
        ),
        migrations.AddField(
            model_name='task',
            name='workstream_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstream_tasks', to='tasks.lookupvalue'),
        ),
        migrations.CreateModel(
            name='RiskIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('risk', 'Risk'), ('issue', 'Issue')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(default='open', max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks_and_issues', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks_and_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks_and_issues', to='tasks.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks_and_issues', to='tasks.workspace')),
            ],
            options={
                'ordering': ['kind', '-severity', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_history', to='tasks.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_change_history', to='tasks.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCodeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('task_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_code_registry', to='tasks.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_task_supporters', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_links', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_supporter_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='supporters',
            field=models.ManyToManyField(related_name='task_support_roles', through='tasks.TaskSupporter', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_execution_foundation, noop_reverse),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='task_progress_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='lookupvalue',
            constraint=models.UniqueConstraint(fields=('workspace', 'project', 'kind', 'slug'), name='unique_scoped_lookup_value'),
        ),
        migrations.AddConstraint(
            model_name='taskcoderegistry',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_reserved_task_code'),
        ),
        migrations.AddConstraint(
            model_name='tasksupporter',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='unique_task_supporter'),
        ),
    ]
