# Generated by Django 5.2.17 on 2026-09-03 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_execution_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lookupvalue',
            index=models.Index(fields=['workspace', 'kind', 'is_active'], name='lookup_ws_kind_active_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='project_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='riskissue',
            index=models.Index(fields=['workspace', 'project', 'kind', 'archived_at'], name='risk_scope_kind_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'state', 'due_date'], name='task_ws_state_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'project_ref', 'status'], name='task_ws_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['workspace', 'assignee', 'status'], name='task_ws_owner_status_idx'),
        ),
    ]
