# Generated by Django 5.2.17 on 2026-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_execution_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedview',
            name='project_scope',
            field=models.CharField(default='all', max_length=80),
        ),
    ]
