# Generated by Django 5.2.17 on 2026-09-03 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_savedview_project_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('break_seconds', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='tasks.workspace')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', 'date'], name='tasks_works_workspa_4e65d3_idx'), models.Index(fields=['user', 'date'], name='tasks_works_user_id_ac3f4e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('workspace', 'user'), name='unique_open_work_shift')],
            },
        ),
    ]
