# Generated by Django 5.2.17 on 2026-09-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='planbucket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
