# Generated by Django 5.2.17 on 2026-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_planbucket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='break_plan_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
