# Generated by Django 5.2.17 on 2026-09-03 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_workshift_break_plan_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='calendar_feed_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='WorkspaceWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('generic', 'Generic JSON')], default='teams', max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='tasks.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
