# Generated by Django 5.2.17 on 2026-09-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_projecttemplate_tasktemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('resource_type', models.CharField(choices=[('person', 'Person'), ('equipment', 'Equipment'), ('budget', 'Budget'), ('other', 'Other')], default='person', max_length=20)),
                ('availability', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.project')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('influence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('interest', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='tasks.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
