# Generated by Django 5.2.17 on 2026-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_workspacesetting_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetting',
            name='ai_default_provider',
            field=models.CharField(default='openai', max_length=30),
        ),
        migrations.AddField(
            model_name='workspacesetting',
            name='ai_enabled_providers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
