# Generated by Django 5.2.17 on 2026-09-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_workspacesetting_ai_default_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='shared_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='shared_files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='shared_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='shared_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
