# Generated by Django 5.2.17 on 2026-09-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_chatmessage_shared_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetting',
            name='ai_provider_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
