# Generated by Django 5.2.17 on 2026-09-04 09:15

import django.db.models.deletion
import tasks.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_workspacesetting_ai_provider_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetting',
            name='screen_capture_interval_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='workspacesetting',
            name='screen_capture_retention_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='workspacesetting',
            name='screen_sharing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacesetting',
            name='screen_sharing_policy',
            field=models.TextField(default='Screen sharing is optional and starts only after the employee accepts a request and chooses a screen or window in the browser. WorkSpace captures screenshots only while sharing is active, never captures audio or webcam data, and lets the employee stop at any time. Authorised workspace leaders can view, download, or delete captures; every such action is audited. Captures expire automatically after the configured retention period.'),
        ),
        migrations.AddField(
            model_name='workspacesetting',
            name='screen_sharing_policy_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ScreenShareSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending consent'), ('active', 'Active'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('policy_text', models.TextField()),
                ('policy_version', models.PositiveIntegerField()),
                ('capture_interval_seconds', models.PositiveSmallIntegerField(default=60)),
                ('capture_retention_days', models.PositiveSmallIntegerField(default=7)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_share_sessions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_screen_share_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_share_sessions', to='tasks.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=tasks.models.private_screen_capture_storage, upload_to='screen-captures/%Y/%m/%d/')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screen_captures', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_captures', to='tasks.workspace')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='tasks.screensharesession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='screensharesession',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='tasks_scree_workspa_cd477e_idx'),
        ),
        migrations.AddIndex(
            model_name='screensharesession',
            index=models.Index(fields=['employee', 'status'], name='tasks_scree_employe_94d6c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='screensharesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('workspace', 'employee'), name='one_open_screen_share_per_employee'),
        ),
        migrations.AddIndex(
            model_name='screencapture',
            index=models.Index(fields=['workspace', 'expires_at'], name='tasks_scree_workspa_d77862_idx'),
        ),
        migrations.AddIndex(
            model_name='screencapture',
            index=models.Index(fields=['session', 'captured_at'], name='tasks_scree_session_ccc39b_idx'),
        ),
    ]
