# Generated by Django 5.2.17 on 2026-09-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0045_repair_document_collaboration_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacedocument',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet')], default='document', max_length=20),
        ),
    ]
