# Generated by Django 5.2.17 on 2026-09-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_alter_workspacedocument_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('software', 'Software'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tasks.project')),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
            },
        ),
    ]
