# Generated by Django 5.2.17 on 2026-09-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_project_budget_amount_project_budget_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling')], default='USD', max_length=8),
        ),
    ]
