# Generated by Django 5.2.17 on 2026-09-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_remove_workspaceinvitation_unique_workspace_invitation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
