# Generated by Django 5.2.17 on 2026-09-07 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_chat_reactions_and_default_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='receipt_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='allocation_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='capacity_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='file_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='role',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_resources', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='escalation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_and_issues', to='tasks.projectexpense'),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='impact',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='likelihood',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='mitigation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskissue',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks_and_issues', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.CharField(choices=[('person', 'Person'), ('equipment', 'Equipment'), ('supplier', 'Supplier'), ('file', 'File'), ('other', 'Other')], default='person', max_length=20),
        ),
    ]
