# Generated by Django 5.2.17 on 2026-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_project_operational_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='manager_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacenotification',
            name='group_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
