# Generated by Django 5.2.17 on 2026-09-07 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0057_merge_notifications_and_workspace_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.directmessage'),
        ),
    ]
