# Generated by Django 5.2.17 on 2026-09-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_direct_message_replies'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planbucket',
            name='unique_plan_bucket_name',
        ),
        migrations.AddField(
            model_name='planbucket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_buckets', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='planbucket',
            name='workstream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_buckets', to='tasks.lookupvalue'),
        ),
        migrations.AddConstraint(
            model_name='planbucket',
            constraint=models.UniqueConstraint(fields=('workspace', 'project', 'workstream', 'name'), name='unique_scoped_plan_bucket_name'),
        ),
    ]
