# Generated by Django 5.2.12 on 2026-09-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0060_add_profile_work_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_comments', to=settings.AUTH_USER_MODEL)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.checkin')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
