# Generated by Django 5.2.17 on 2026-09-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0063_notificationpreference_notification_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetting',
            name='check_in_reminder_hour',
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
