# Generated by Django 5.2.17 on 2026-09-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0066_restore_buckets_for_orphaned_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('summary', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_ai_actions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_actions', to='tasks.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'requested_by', 'status'], name='ai_action_ws_user_status_idx')],
            },
        ),
    ]
