# Generated by Django 5.2.17 on 2026-09-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0073_prune_direct_conversation_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_sound_name',
            field=models.CharField(choices=[('chime', 'Chime'), ('bell', 'Bell'), ('pop', 'Pop'), ('pulse', 'Pulse')], default='chime', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_volume',
            field=models.PositiveSmallIntegerField(default=70),
        ),
    ]
