# Generated by Django 5.2.17 on 2026-09-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0078_activityevent_related_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacenotification',
            options={'ordering': [models.OrderBy(models.F('read_at'), nulls_first=True), '-created_at']},
        ),
    ]
