# Generated by Django 5.2.17 on 2026-09-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0079_alter_workspacenotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimate_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_capacity_minutes',
            field=models.PositiveIntegerField(default=2400),
        ),
    ]
