# Generated by Django 5.2.17 on 2026-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0080_task_estimate_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='daily_capacity_minutes',
            field=models.PositiveIntegerField(default=480),
        ),
        migrations.AddField(
            model_name='membership',
            name='weekly_capacity_minutes',
            field=models.PositiveIntegerField(default=2400),
        ),
    ]
