# Generated by Django 5.2.17 on 2026-09-21 17:48

import tasks.models
from django.db import migrations, models
from django.db.models import F


def backfill_weekly_capacity(apps, schema_editor):
    Membership = apps.get_model('tasks', 'Membership')
    Membership.objects.update(weekly_capacity_minutes=F('daily_capacity_minutes') * 5)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0081_membership_daily_capacity_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='working_days',
            field=models.JSONField(default=tasks.models.default_working_days),
        ),
        migrations.RunPython(backfill_weekly_capacity, migrations.RunPython.noop),
    ]
