# Generated by Django 5.2.17 on 2026-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0082_membership_working_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='cloudinary_asset',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cloudinary_asset',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspacefile',
            name='cloudinary_asset',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
