# Generated by Django 5.2.17 on 2026-09-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0083_taskattachment_cloudinary_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='cloudinary_asset',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workspace-logos/%Y/%m/'),
        ),
    ]
