# Generated by Django 5.2.17 on 2026-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0084_workspace_cloudinary_asset_workspace_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
