# Generated by Django 5.2.17 on 2026-10-06 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0086_ai_chat_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetting',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('messages', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveBigIntegerField(default=0)),
                ('completion_tokens', models.PositiveBigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='tasks.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'day'], name='ai_usage_ws_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user', 'day'), name='unique_ai_usage_per_user_day')],
            },
        ),
    ]
