# Generated by Django 5.2.17 on 2026-10-06 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_people_already_working_on_each_board(apps, schema_editor):
    """Boards become members-only, so keep everyone who already works on one on it.

    Without this, a member whose tasks sit on a project or workstream board would
    lose sight of their own work the moment the rule took effect, and the owner
    would have to rebuild every list by hand. Anyone who is assigned to a task,
    or supports one, on a board is added to that board; nobody else is.
    """
    Task = apps.get_model('tasks', 'Task')
    Project = apps.get_model('tasks', 'Project')
    LookupValue = apps.get_model('tasks', 'LookupValue')

    def people(tasks):
        found = set()
        for task in tasks.prefetch_related('assignee_links', 'supporters'):
            if task.assignee_id:
                found.add(task.assignee_id)
            found.update(link.user_id for link in task.assignee_links.all())
            found.update(user.id for user in task.supporters.all())
        return found

    for project in Project.objects.all():
        project.members.add(*people(Task.objects.filter(project_ref_id=project.id)))
    for stream in LookupValue.objects.filter(kind='workstream'):
        stream.members.add(*people(Task.objects.filter(workstream_ref_id=stream.id)))


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0087_ai_usage_and_daily_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupvalue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lookupvalue',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookupvalue',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_workstreams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(add_people_already_working_on_each_board, migrations.RunPython.noop),
    ]
